title: "Matthijs van der Veer's Blog"
description: "A blog by Matthijs van der Veer."
url: "https://www.vanderveer.io"
baseurl: ""

permalink: /:title/

# Author
author: "Matthijs van der Veer"
author_bio: "Cloud & AI consultant at Xebia. Public speaker. I cut through the hype and make AI digestible for engineers and executives alike. Honestly though, I'm just here to earn the kibble for my dog."
author_photo: /assets/profile.png

# Social links
social:
  github: "https://github.com/MatthijsvdVeer"
  linkedin: "https://www.linkedin.com/in/matthijsvanderveer/"

# Build settings
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima theme settings
header_pages:
  - about.md

# Google Analytics
google_analytics: UA-121896968-3

# Feed settings
feed:
  path: feed.xml

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - LICENSE
  - README.md

collections:
  books:
    output: false